sudo: true
language: node_js
node_js: '8'
os: osx
osx_image: xcode8.3

branches:
  only:
  - master

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
  - npm install
  - ./node_modules/.bin/webpack -p

script:
  - "./node_modules/.bin/build --config ./electron-builder.yml --mac -p always"
