sudo: true
language: node_js
node_js: '8'
os: osx
osx_image: xcode8

branches:
  only:
  - master

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
  - npm install --registry=https://registry.npm.taobao.org
  - ./node_modules/.bin/webpack -p
  - npm run build

script:
  - "./node_modules/.bin/build --config ./electron-builder.yml --mac -p always"
